"""

Revision ID: 66d38135fada
Revises: a66a158f54f9
Create Date: 2024-10-03 15:49:46.742784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d38135fada'
down_revision: Union[str, None] = 'a66a158f54f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kittens', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kittens', 'age_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kittens', 'age_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kittens', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
