"""

Revision ID: 70986331f6ac
Revises: 1016fbf1380a
Create Date: 2024-10-03 17:36:58.166302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70986331f6ac'
down_revision: Union[str, None] = '1016fbf1380a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kittens', 'info_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kittens', 'info_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
