"""

Revision ID: ef3b75860479
Revises: 1f5f67b444b3
Create Date: 2024-10-03 16:44:26.090813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3b75860479'
down_revision: Union[str, None] = '1f5f67b444b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitten_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('kittens', sa.Column('info_id', sa.Integer(), nullable=False))
    op.drop_constraint('kittens_breed_id_fkey', 'kittens', type_='foreignkey')
    op.create_foreign_key(None, 'kittens', 'kitten_info', ['info_id'], ['id'])
    op.drop_column('kittens', 'breed_id')
    op.drop_column('kittens', 'age_months')
    op.drop_column('kittens', 'color')
    op.drop_column('kittens', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kittens', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kittens', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kittens', sa.Column('age_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kittens', sa.Column('breed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'kittens', type_='foreignkey')
    op.create_foreign_key('kittens_breed_id_fkey', 'kittens', 'breeds', ['breed_id'], ['id'])
    op.drop_column('kittens', 'info_id')
    op.drop_table('kitten_info')
    # ### end Alembic commands ###
